name: Update Down Detector

on:
  schedule:
    - cron: '*/10 * * * *'  # Každých 10 minut
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "<!-- Aktualizováno: $(date) -->" > update.log

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add update.log
          git commit -m "Automatická aktualizace času"
          git push
